using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WixSharp.Entities.CatalogV3
{
    // Usings are declared inside the namespace so that Common types take precedence over
    // legacy types with the same name in WixSharp.Entities.
    using WixSharp.Entities.Common;

    /// <summary>
    /// A product in a Wix Stores Catalog V3.
    /// Every product has at least one variant; pricing, SKU and inventory status live on the variants.
    /// </summary>
    public class Product
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// Revision number, which increments by 1 each time the product is updated.
        /// The current revision must be passed when updating the product.
        /// </summary>
        [JsonProperty("revision")]
        public string Revision { get; set; }

        [JsonProperty("createdDate")]
        public DateTimeOffset? CreatedDate { get; set; }

        [JsonProperty("updatedDate")]
        public DateTimeOffset? UpdatedDate { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// URL-friendly identifier used in the product page address. Autogenerated from the name if not provided.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug { get; set; }

        /// <summary>
        /// Returned only when <see cref="RequestedProductFields.Url"/> is requested.
        /// </summary>
        [JsonProperty("url")]
        public PageUrl Url { get; set; }

        /// <summary>
        /// Product description as a Ricos rich content document.
        /// Returned only when <see cref="RequestedProductFields.Description"/> is requested.
        /// </summary>
        [JsonProperty("description")]
        public JObject Description { get; set; }

        /// <summary>
        /// Product description in HTML. Ignored on create/update when <see cref="Description"/> is also passed.
        /// Returned only when <see cref="RequestedProductFields.PlainDescription"/> is requested.
        /// </summary>
        [JsonProperty("plainDescription")]
        public string PlainDescription { get; set; }

        [JsonProperty("visible")]
        public bool? Visible { get; set; }

        [JsonProperty("visibleInPos")]
        public bool? VisibleInPos { get; set; }

        [JsonProperty("media")]
        public Media Media { get; set; }

        [JsonProperty("seoData")]
        public JObject SeoData { get; set; }

        [JsonProperty("taxGroupId")]
        public string TaxGroupId { get; set; }

        /// <summary>
        /// Product options, such as "Size" or "Color". Options always create variants.
        /// </summary>
        [JsonProperty("options")]
        public List<ConnectedOption> Options { get; set; }

        /// <summary>
        /// Product modifiers. Collect additional information from customers without creating variants
        /// (V1 options with manageVariants=false and V1 custom text fields are modifiers in V3).
        /// </summary>
        [JsonProperty("modifiers")]
        public List<ConnectedModifier> Modifiers { get; set; }

        [JsonProperty("brand")]
        public Brand Brand { get; set; }

        [JsonProperty("infoSections")]
        public List<InfoSection> InfoSections { get; set; }

        [JsonProperty("ribbon")]
        public Ribbon Ribbon { get; set; }

        /// <summary>
        /// Categories the product is directly assigned to.
        /// Returned only when <see cref="RequestedProductFields.DirectCategoriesInfo"/> is requested.
        /// </summary>
        [JsonProperty("directCategoriesInfo")]
        public ProductCategoriesInfo DirectCategoriesInfo { get; set; }

        /// <summary>
        /// All categories the product belongs to, including parent categories.
        /// Returned only when <see cref="RequestedProductFields.AllCategoriesInfo"/> is requested.
        /// </summary>
        [JsonProperty("allCategoriesInfo")]
        public ProductCategoriesInfo AllCategoriesInfo { get; set; }

        [JsonProperty("mainCategoryId")]
        public string MainCategoryId { get; set; }

        /// <summary>
        /// Returned only when <see cref="RequestedProductFields.MerchantData"/> is requested.
        /// </summary>
        [JsonProperty("costRange")]
        public PriceRange CostRange { get; set; }

        /// <summary>
        /// Aggregated inventory status of the default location. Read-only.
        /// </summary>
        [JsonProperty("inventory")]
        public ProductInventory Inventory { get; set; }

        /// <summary>
        /// See <see cref="ProductTypes"/>.
        /// </summary>
        [JsonProperty("productType")]
        public string ProductType { get; set; }

        /// <summary>
        /// Required when <see cref="ProductType"/> is <see cref="ProductTypes.Physical"/>.
        /// </summary>
        [JsonProperty("physicalProperties")]
        public PhysicalProperties PhysicalProperties { get; set; }

        /// <summary>
        /// A unique human-friendly identifier that, unlike <see cref="Id"/>, can be set when creating the product.
        /// </summary>
        [JsonProperty("handle")]
        public string Handle { get; set; }

        /// <summary>
        /// ISO-4217 currency code of the product prices.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("breadcrumbsInfo")]
        public BreadcrumbsInfo BreadcrumbsInfo { get; set; }

        /// <summary>
        /// Minimum and maximum selling prices across all variants. Read-only.
        /// </summary>
        [JsonProperty("actualPriceRange")]
        public PriceRange ActualPriceRange { get; set; }

        /// <summary>
        /// Minimum and maximum compare-at (strikethrough) prices across all variants. Read-only.
        /// </summary>
        [JsonProperty("compareAtPriceRange")]
        public PriceRange CompareAtPriceRange { get; set; }

        [JsonProperty("variantsInfo")]
        public VariantsInfo VariantsInfo { get; set; }

        [JsonProperty("purchaseEligibility")]
        public PurchaseEligibility PurchaseEligibility { get; set; }

        [JsonProperty("additionalRibbons")]
        public List<Ribbon> AdditionalRibbons { get; set; }

        [JsonProperty("extendedFields")]
        public ExtendedFields ExtendedFields { get; set; }

        [JsonProperty("tags")]
        public ProductTags Tags { get; set; }

        [JsonProperty("subscriptionDetails")]
        public SubscriptionDetails SubscriptionDetails { get; set; }

        [JsonProperty("variantSummary")]
        public VariantSummary VariantSummary { get; set; }
    }

    public class PageUrl
    {
        /// <summary>
        /// Relative path of the page within the site, e.g. "/product-page/a-product".
        /// </summary>
        [JsonProperty("relativePath")]
        public string RelativePath { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public class Media
    {
        /// <summary>
        /// Main media item. Automatically set to the first item in <see cref="ItemsInfo"/>.
        /// </summary>
        [JsonProperty("main")]
        public ProductMedia Main { get; set; }

        /// <summary>
        /// All media items. Returned only when <see cref="RequestedProductFields.MediaItemsInfo"/> is requested.
        /// </summary>
        [JsonProperty("itemsInfo")]
        public MediaItemsInfo ItemsInfo { get; set; }
    }

    public class MediaItemsInfo
    {
        [JsonProperty("items")]
        public List<ProductMedia> Items { get; set; }
    }

    public class ProductMedia
    {
        /// <summary>
        /// ID of an existing Wix Media item. Set either this, <see cref="Url"/>, <see cref="Image"/> or <see cref="Video"/>.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// URL of media to upload to the Wix Media Manager.
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("image")]
        public WixImage Image { get; set; }

        [JsonProperty("video")]
        public VideoV2 Video { get; set; }

        [JsonProperty("altText")]
        public string AltText { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// "IMAGE" or "VIDEO". Read-only.
        /// </summary>
        [JsonProperty("mediaType")]
        public string MediaType { get; set; }

        /// <summary>
        /// Returned only when <see cref="RequestedProductFields.Thumbnail"/> is requested.
        /// </summary>
        [JsonProperty("thumbnail")]
        public Thumbnail Thumbnail { get; set; }

        [JsonProperty("uploadId")]
        public string UploadId { get; set; }
    }

    public class Thumbnail
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("height")]
        public int? Height { get; set; }

        [JsonProperty("width")]
        public int? Width { get; set; }

        [JsonProperty("altText")]
        public string AltText { get; set; }
    }

    public class VideoV2
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("resolutions")]
        public List<VideoResolution> Resolutions { get; set; }

        [JsonProperty("filename")]
        public string Filename { get; set; }
    }

    public class VideoResolution
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("height")]
        public int? Height { get; set; }

        [JsonProperty("width")]
        public int? Width { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }
    }

    public class ConnectedOption
    {
        /// <summary>
        /// ID of a customization with customizationType PRODUCT_OPTION.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// "TEXT_CHOICES" or "SWATCH_CHOICES".
        /// </summary>
        [JsonProperty("optionRenderType")]
        public string OptionRenderType { get; set; }

        /// <summary>
        /// Read-only identifier generated from the option name. Use it in eCommerce <c>catalogReference.options</c>.
        /// </summary>
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("choicesSettings")]
        public ChoicesSettings ChoicesSettings { get; set; }
    }

    public class ChoicesSettings
    {
        [JsonProperty("choices")]
        public List<ConnectedOptionChoice> Choices { get; set; }
    }

    public class ConnectedOptionChoice
    {
        [JsonProperty("choiceId")]
        public string ChoiceId { get; set; }

        /// <summary>
        /// "CHOICE_TEXT" or "ONE_COLOR".
        /// </summary>
        [JsonProperty("choiceType")]
        public string ChoiceType { get; set; }

        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Hex color code, for <c>ONE_COLOR</c> choices.
        /// </summary>
        [JsonProperty("colorCode")]
        public string ColorCode { get; set; }

        [JsonProperty("inStock")]
        public bool? InStock { get; set; }

        [JsonProperty("visible")]
        public bool? Visible { get; set; }

        [JsonProperty("displayImage")]
        public WixImage DisplayImage { get; set; }

        [JsonProperty("media")]
        public JObject Media { get; set; }
    }

    public class ConnectedModifier
    {
        /// <summary>
        /// ID of a customization with customizationType MODIFIER.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// "FREE_TEXT", "TEXT_CHOICES" or "SWATCH_CHOICES".
        /// </summary>
        [JsonProperty("modifierRenderType")]
        public string ModifierRenderType { get; set; }

        [JsonProperty("key")]
        public string Key { get; set; }

        /// <summary>
        /// Whether customer input is required for this modifier.
        /// </summary>
        [JsonProperty("mandatory")]
        public bool? Mandatory { get; set; }

        [JsonProperty("freeTextSettings")]
        public FreeTextSettings FreeTextSettings { get; set; }

        [JsonProperty("choicesSettings")]
        public ModifierChoicesSettings ChoicesSettings { get; set; }
    }

    public class FreeTextSettings
    {
        [JsonProperty("minCharCount")]
        public int? MinCharCount { get; set; }

        [JsonProperty("maxCharCount")]
        public int? MaxCharCount { get; set; }

        [JsonProperty("defaultAddedPrice")]
        public string DefaultAddedPrice { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("key")]
        public string Key { get; set; }
    }

    public class ModifierChoicesSettings
    {
        [JsonProperty("choices")]
        public List<ConnectedModifierChoice> Choices { get; set; }
    }

    public class ConnectedModifierChoice
    {
        [JsonProperty("choiceId")]
        public string ChoiceId { get; set; }

        [JsonProperty("choiceType")]
        public string ChoiceType { get; set; }

        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("colorCode")]
        public string ColorCode { get; set; }

        /// <summary>
        /// Price added to the variant price when this choice is selected.
        /// </summary>
        [JsonProperty("addedPrice")]
        public string AddedPrice { get; set; }

        [JsonProperty("displayImage")]
        public WixImage DisplayImage { get; set; }

        [JsonProperty("media")]
        public JObject Media { get; set; }
    }

    public class Brand
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public class Ribbon
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public class InfoSection
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("uniqueName")]
        public string UniqueName { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("description")]
        public JObject Description { get; set; }

        [JsonProperty("plainDescription")]
        public string PlainDescription { get; set; }
    }

    public class ProductCategoriesInfo
    {
        [JsonProperty("categories")]
        public List<ProductCategory> Categories { get; set; }
    }

    public class ProductCategory
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// Position of the product within the category.
        /// </summary>
        [JsonProperty("index")]
        public int? Index { get; set; }
    }

    public class PriceRange
    {
        [JsonProperty("minValue")]
        public FixedMonetaryAmount MinValue { get; set; }

        [JsonProperty("maxValue")]
        public FixedMonetaryAmount MaxValue { get; set; }
    }

    public class FixedMonetaryAmount
    {
        /// <summary>
        /// Monetary amount as a decimal string, e.g. "3.99".
        /// </summary>
        [JsonProperty("amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Amount formatted with the currency, e.g. "$3.99". Returned only when <see cref="RequestedProductFields.Currency"/> is requested.
        /// </summary>
        [JsonProperty("formattedAmount")]
        public string FormattedAmount { get; set; }
    }

    public class ProductInventory
    {
        /// <summary>
        /// "IN_STOCK", "OUT_OF_STOCK" or "PARTIALLY_OUT_OF_STOCK".
        /// </summary>
        [JsonProperty("availabilityStatus")]
        public string AvailabilityStatus { get; set; }

        /// <summary>
        /// "ENABLED", "DISABLED" or "PARTIALLY_ENABLED".
        /// </summary>
        [JsonProperty("preorderStatus")]
        public string PreorderStatus { get; set; }

        /// <summary>
        /// "ALL_VARIANTS", "NO_VARIANTS" or "SOME_VARIANTS".
        /// </summary>
        [JsonProperty("preorderAvailability")]
        public string PreorderAvailability { get; set; }
    }

    public class PhysicalProperties
    {
        /// <summary>
        /// Price per unit settings, e.g. for products sold by weight or volume.
        /// </summary>
        [JsonProperty("pricePerUnit")]
        public PricePerUnitSettings PricePerUnit { get; set; }

        [JsonProperty("fulfillerId")]
        public string FulfillerId { get; set; }

        [JsonProperty("shippingWeightRange")]
        public WeightRange ShippingWeightRange { get; set; }

        [JsonProperty("pricePerUnitRange")]
        public PricePerUnitRange PricePerUnitRange { get; set; }

        /// <summary>
        /// Returned only when <see cref="RequestedProductFields.WeightMeasurementUnitInfo"/> is requested.
        /// </summary>
        [JsonProperty("weightMeasurementUnitInfo")]
        public WeightMeasurementUnitInfo WeightMeasurementUnitInfo { get; set; }

        [JsonProperty("deliveryProfileId")]
        public string DeliveryProfileId { get; set; }
    }

    public class PricePerUnitSettings
    {
        /// <summary>
        /// Quantity, e.g. 100 to define price per 100 grams.
        /// </summary>
        [JsonProperty("quantity")]
        public decimal? Quantity { get; set; }

        /// <summary>
        /// Measurement unit, e.g. "G", "KG", "ML", "L", "M", "LB".
        /// </summary>
        [JsonProperty("measurementUnit")]
        public string MeasurementUnit { get; set; }
    }

    public class PricePerUnit
    {
        [JsonProperty("settings")]
        public PricePerUnitSettings Settings { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public class WeightRange
    {
        [JsonProperty("minValue")]
        public decimal? MinValue { get; set; }

        [JsonProperty("maxValue")]
        public decimal? MaxValue { get; set; }
    }

    public class PricePerUnitRange
    {
        [JsonProperty("minValue")]
        public PricePerUnit MinValue { get; set; }

        [JsonProperty("maxValue")]
        public PricePerUnit MaxValue { get; set; }
    }

    public class WeightMeasurementUnitInfo
    {
        /// <summary>
        /// "KG" or "LB".
        /// </summary>
        [JsonProperty("weightMeasurementUnit")]
        public string WeightMeasurementUnit { get; set; }
    }

    public class BreadcrumbsInfo
    {
        [JsonProperty("breadcrumbs")]
        public List<Breadcrumb> Breadcrumbs { get; set; }
    }

    public class Breadcrumb
    {
        [JsonProperty("categoryId")]
        public string CategoryId { get; set; }

        [JsonProperty("categoryName")]
        public string CategoryName { get; set; }

        [JsonProperty("categorySlug")]
        public string CategorySlug { get; set; }
    }

    public class VariantsInfo
    {
        [JsonProperty("variants")]
        public List<Variant> Variants { get; set; }
    }

    public class Variant
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("visible")]
        public bool? Visible { get; set; }

        [JsonProperty("sku")]
        public string Sku { get; set; }

        [JsonProperty("barcode")]
        public string Barcode { get; set; }

        /// <summary>
        /// Choices that define this variant: exactly one choice per product option. Empty for single-variant products.
        /// </summary>
        [JsonProperty("choices")]
        public List<OptionChoice> Choices { get; set; }

        [JsonProperty("price")]
        public PriceInfo Price { get; set; }

        /// <summary>
        /// Returned only when <see cref="RequestedProductFields.MerchantData"/> is requested.
        /// </summary>
        [JsonProperty("revenueDetails")]
        public RevenueDetails RevenueDetails { get; set; }

        [JsonProperty("media")]
        public ProductMedia Media { get; set; }

        [JsonProperty("subscriptionPricesInfo")]
        public JObject SubscriptionPricesInfo { get; set; }

        /// <summary>
        /// Read-only inventory status of the variant in the default location.
        /// </summary>
        [JsonProperty("inventoryStatus")]
        public InventoryStatus InventoryStatus { get; set; }

        [JsonProperty("physicalProperties")]
        public VariantPhysicalProperties PhysicalProperties { get; set; }

        [JsonProperty("digitalProperties")]
        public VariantDigitalProperties DigitalProperties { get; set; }

        /// <summary>
        /// Inventory of the variant in the default location.
        /// Used only by the "with inventory" endpoints (create/update product with inventory).
        /// </summary>
        [JsonProperty("inventoryItem")]
        public VariantInventoryItem InventoryItem { get; set; }
    }

    public class OptionChoice
    {
        [JsonProperty("optionChoiceIds")]
        public OptionChoiceIds OptionChoiceIds { get; set; }

        /// <summary>
        /// Returned only when <see cref="RequestedProductFields.VariantOptionChoiceNames"/> is requested.
        /// Can be passed instead of IDs when creating a product.
        /// </summary>
        [JsonProperty("optionChoiceNames")]
        public OptionChoiceNames OptionChoiceNames { get; set; }
    }

    public class OptionChoiceIds
    {
        [JsonProperty("optionId")]
        public string OptionId { get; set; }

        [JsonProperty("choiceId")]
        public string ChoiceId { get; set; }
    }

    public class OptionChoiceNames
    {
        [JsonProperty("optionName")]
        public string OptionName { get; set; }

        [JsonProperty("choiceName")]
        public string ChoiceName { get; set; }

        [JsonProperty("renderType")]
        public string RenderType { get; set; }
    }

    public class PriceInfo
    {
        /// <summary>
        /// The selling price. Required when creating a variant.
        /// </summary>
        [JsonProperty("actualPrice")]
        public FixedMonetaryAmount ActualPrice { get; set; }

        /// <summary>
        /// The original price, displayed as strikethrough when higher than <see cref="ActualPrice"/>.
        /// </summary>
        [JsonProperty("compareAtPrice")]
        public FixedMonetaryAmount CompareAtPrice { get; set; }

        /// <summary>
        /// Returned only when <see cref="RequestedProductFields.DiscountInfo"/> is requested.
        /// </summary>
        [JsonProperty("priceAfterDiscount")]
        public FixedMonetaryAmount PriceAfterDiscount { get; set; }
    }

    public class RevenueDetails
    {
        [JsonProperty("cost")]
        public FixedMonetaryAmount Cost { get; set; }

        [JsonProperty("profit")]
        public FixedMonetaryAmount Profit { get; set; }

        [JsonProperty("profitMargin")]
        public decimal? ProfitMargin { get; set; }
    }

    public class InventoryStatus
    {
        [JsonProperty("inStock")]
        public bool? InStock { get; set; }

        [JsonProperty("preorderEnabled")]
        public bool? PreorderEnabled { get; set; }
    }

    public class VariantInventoryItem
    {
        /// <summary>
        /// Tracking method: in stock / out of stock, without a quantity limit. Set either this or <see cref="Quantity"/>.
        /// </summary>
        [JsonProperty("inStock")]
        public bool? InStock { get; set; }

        /// <summary>
        /// Tracking method: quantity left in inventory. Set either this or <see cref="InStock"/>.
        /// </summary>
        [JsonProperty("quantity")]
        public int? Quantity { get; set; }

        [JsonProperty("preorderInfo")]
        public PreorderInfo PreorderInfo { get; set; }
    }

    public class VariantPhysicalProperties
    {
        /// <summary>
        /// Variant shipping weight, in the site's weight unit.
        /// </summary>
        [JsonProperty("weight")]
        public decimal? Weight { get; set; }

        [JsonProperty("pricePerUnit")]
        public PricePerUnit PricePerUnit { get; set; }

        [JsonProperty("productDimensions")]
        public Dimensions ProductDimensions { get; set; }

        [JsonProperty("packageDimensions")]
        public Dimensions PackageDimensions { get; set; }
    }

    public class Dimensions
    {
        [JsonProperty("length")]
        public string Length { get; set; }

        [JsonProperty("width")]
        public string Width { get; set; }

        [JsonProperty("height")]
        public string Height { get; set; }

        /// <summary>
        /// "MM", "CM", "M", "IN", "FT" or "YD".
        /// </summary>
        [JsonProperty("unit")]
        public string Unit { get; set; }
    }

    public class VariantDigitalProperties
    {
        [JsonProperty("digitalFile")]
        public SecuredMedia DigitalFile { get; set; }
    }

    public class SecuredMedia
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("fileName")]
        public string FileName { get; set; }

        [JsonProperty("fileSize")]
        public string FileSize { get; set; }

        [JsonProperty("fileType")]
        public string FileType { get; set; }
    }

    public class PurchaseEligibility
    {
        [JsonProperty("userCriteria")]
        public string UserCriteria { get; set; }
    }

    public class ProductTags
    {
        /// <summary>
        /// Tags that require an additional permission to access, normally not given to site members or visitors.
        /// </summary>
        [JsonProperty("privateTags")]
        public TagList PrivateTags { get; set; }

        [JsonProperty("publicTags")]
        public TagList PublicTags { get; set; }
    }

    public class SubscriptionDetails
    {
        [JsonProperty("subscriptions")]
        public List<Subscription> Subscriptions { get; set; }

        [JsonProperty("allowOneTimePurchases")]
        public bool? AllowOneTimePurchases { get; set; }
    }

    public class Subscription
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("visible")]
        public bool? Visible { get; set; }

        /// <summary>
        /// "DAY", "WEEK", "MONTH" or "YEAR".
        /// </summary>
        [JsonProperty("frequency")]
        public string Frequency { get; set; }

        [JsonProperty("interval")]
        public int? Interval { get; set; }

        /// <summary>
        /// Whether the subscription renews automatically. Set either this or <see cref="BillingCycles"/>.
        /// </summary>
        [JsonProperty("autoRenewal")]
        public bool? AutoRenewal { get; set; }

        [JsonProperty("billingCycles")]
        public int? BillingCycles { get; set; }

        [JsonProperty("discount")]
        public SubscriptionDiscount Discount { get; set; }
    }

    public class SubscriptionDiscount
    {
        [JsonProperty("amountOff")]
        public string AmountOff { get; set; }

        [JsonProperty("percentOff")]
        public decimal? PercentOff { get; set; }

        /// <summary>
        /// "AMOUNT" or "PERCENT".
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public class VariantSummary
    {
        [JsonProperty("variantCount")]
        public int? VariantCount { get; set; }

        /// <summary>
        /// The visible variant with the lowest actual price.
        /// Returned only when <see cref="RequestedProductFields.MinPriceVariant"/> is requested.
        /// </summary>
        [JsonProperty("minPriceVariant")]
        public Variant MinPriceVariant { get; set; }
    }

    public static class ProductTypes
    {
        public const string Physical = "PHYSICAL";
        public const string Digital = "DIGITAL";
    }

    /// <summary>
    /// Values for the <c>fields</c> parameter of Products V3 endpoints. Each one adds data that isn't returned by default.
    /// </summary>
    public static class RequestedProductFields
    {
        public const string Url = "URL";
        public const string Currency = "CURRENCY";
        public const string InfoSection = "INFO_SECTION";
        /// <summary>Requires the SCOPE.STORES.PRODUCT_READ_ADMIN permission.</summary>
        public const string MerchantData = "MERCHANT_DATA";
        public const string PlainDescription = "PLAIN_DESCRIPTION";
        public const string InfoSectionPlainDescription = "INFO_SECTION_PLAIN_DESCRIPTION";
        public const string SubscriptionPricesInfo = "SUBSCRIPTION_PRICES_INFO";
        public const string BreadcrumbsInfo = "BREADCRUMBS_INFO";
        public const string WeightMeasurementUnitInfo = "WEIGHT_MEASUREMENT_UNIT_INFO";
        public const string VariantOptionChoiceNames = "VARIANT_OPTION_CHOICE_NAMES";
        public const string MediaItemsInfo = "MEDIA_ITEMS_INFO";
        public const string Description = "DESCRIPTION";
        public const string DirectCategoriesInfo = "DIRECT_CATEGORIES_INFO";
        public const string AllCategoriesInfo = "ALL_CATEGORIES_INFO";
        public const string InfoSectionDescription = "INFO_SECTION_DESCRIPTION";
        public const string Thumbnail = "THUMBNAIL";
        public const string ProductChoicesMediaReferences = "PRODUCT_CHOICES_MEDIA_REFERENCES";
        public const string ProductChoicesDisplayImage = "PRODUCT_CHOICES_DISPLAY_IMAGE";
        /// <summary>Populates <c>variantSummary.minPriceVariant</c>. Query and Search Products only.</summary>
        public const string MinPriceVariant = "MIN_PRICE_VARIANT";
        public const string DiscountInfo = "DISCOUNT_INFO";
    }
}
